---
# S3Stor Configuration
s3stor_volume_port: 8080
s3stor_volume_data_directory: /data
s3stor_volume_datacenter: dc1
s3stor_volume_rack: rack1
s3stor_volume_compaction_speed: 50
s3stor_volume_file_size_limit: 5242880
s3stor_volume_metrics_port: 9325
s3stor_volume_data_pool_name: rpool
s3stor_volume_data_directory_size: 10G
s3stor_volume_max_volumes: 300

# Become Settings
ansible_timeout: 60
ansible_user: 
# ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_ssh_pass: ""
ansible_become: true
ansible_become_method: sudo
ansible_become_user: root
ansible_become_timeout: 60
ansible_become_ask_pass: false
ansible_ssh_common_args: '-o ConnectTimeout=60 -o ServerAliveInterval=60 -o IdentitiesOnly=yes'
ansible_python_interpreter: auto_silent
